services:
  db:
    image: postgres:16-alpine
    container_name: chat_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d # База выполнит наш SQL при старте

  app-server:
    build:
      context: .
      target: server-runner
    container_name: chat_server
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/chat_db
      - DB_USER=user
      - DB_PASS=password

volumes:
  db_data: